##
# Course Work Python
#
# @file
# @version 0.1

# Misc
.PHONY: test
test:
	python3 test.py

# Part 1
.PHONY: plot_data
plot_data:
	python3 plot_data.py

# Setup
.PHONY: setup setup_sliding

setup: setup.py
	python3 setup.py

setup_sliding: setup_sliding.py
	python3 setup_sliding.py

task_1_2:
	python3 task_1_2.py

task_1_2_sliding:
	python3 task_1_2_sliding.py

rotation_torque:
	python3 rotation_torque.py

task_3:
	python3 task_3.py

task_3_ripple:
	python3 task_3_ripple.py

task_4:
	python3 task_4.py

task_4_measurement:
	python3 task_4_measurement.py

task_5:
	python3 task_5.py

.PHONY: task_1_2 task_1_2_sliding rotation_torque task_3 task_3_ripple task_4 task_4_measurement task_5

# Part 2
task_7: task_7.py
	python3 task_7.py

task_9:
	python3 task_9.py

.PHONY: task_7 task_9

# end
