##
# Course Work Python
#
# @file
# @version 0.1

.PHONY: test
test:
	python3 test.py

task_1_2:
	python3 task_1_2.py

task_1_2_sliding:
	python3 task_1_2_sliding.py

rotation_torque:
	python3 rotation_torque.py

task_3:
	python3 task_3.py

task_3_ripple:
	python3 task_3_ripple.py

task_4:
	python3 task_4.py

task_5:
	python3 task_5.py

.PHONY: task_1_2 task_1_2_sliding rotation_torque task_3 task_3_ripple task_4 task_5

# end
